# Generated by Django 5.2.5 on 2025-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this IP block is active'),
        ),
    ]
