# Generated by Django 5.2.5 on 2025-09-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip_tracking", "0004_requestlog_city_requestlog_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("high_volume", "High request volume"),
                            ("sensitive_path", "Accessed sensitive path"),
                            ("multiple", "Multiple violations"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_detected", models.DateTimeField(auto_now_add=True)),
                ("last_detected", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Suspicious IP",
                "verbose_name_plural": "Suspicious IPs",
                "ordering": ["-last_detected"],
            },
        ),
    ]
