# Generated by Django 5.2.5 on 2025-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_blockedip_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_3489f7_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['country', 'city'], name='ip_tracking_country_98da01_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['timestamp'], name='ip_tracking_timesta_b1bb90_idx'),
        ),
    ]
